language: php
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2

cache:
  directories:
    - ${HOME}/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit -v
