language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - ${HOME}/.composer/cache/files

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  - composer update --no-interaction --no-progress --no-suggest ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit -v
